In [14]:
import pandas as pd
import numpy as np
import re

In [18]:
data = pd.read_csv('./data/processed/processed_temp_data.CSV')
data.head(5)

,Transaction Date,Description,Category,Type,Amount,Merchant,Is_Recurring
0,2025-01-20,PANCHOS MEXICAN GRILL,Food & Drink,Sale,-17.59,panchos mexican grill,False
1,2025-01-20,BP#1027500MIRROR LAKE BP,Gas,Sale,-31.14,bpmirror lake bp,False
2,2025-01-20,LG - MIDTOWN,Food & Drink,Sale,-6.18,lg midtown,False
3,2025-01-20,MARATHON PETRO36889,Gas,Sale,-30.19,marathon petro,False
4,2025-01-18,PANERA BREAD #606169 O,Food & Drink,Sale,-10.52,panera bread o,False

In [19]:
data[data['Is_Recurring']]

,Transaction Date,Description,Category,Type,Amount,Merchant,Is_Recurring
6,2025-01-15,GOOGLE *Colab,Bills & Utilities,Sale,-9.99,google colab,True
7,2025-01-10,OPENAI *CHATGPT SUBSCR,Shopping,Sale,-20.00,openai chatgpt subscr,True
8,2025-01-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
11,2024-12-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True
26,2024-12-15,GOOGLE *Colab,Shopping,Sale,-9.99,google colab,True
29,2024-12-09,OPENAI *CHATGPT SUBSCR,Shopping,Sale,-20.00,openai chatgpt subscr,True
32,2024-12-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
36,2024-11-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True
43,2024-11-15,GOOGLE *Colab,Professional Services,Sale,-9.99,google colab,True
45,2024-11-09,OPENAI *CHATGPT SUBSCR,Shopping,Sale,-20.00,openai chatgpt subscr,True
46,2024-11-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
55,2024-10-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True
61,2024-10-26,Peacock E85A5 Premium,Bills & Utilities,Sale,-2.28,peacock x premium,True
68,2024-10-15,GOOGLE *Colab,Personal,Sale,-9.99,google colab,True
72,2024-10-09,OPENAI *CHATGPT SUBSCR,Shopping,Sale,-20.00,openai chatgpt subscr,True
73,2024-10-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
76,2024-09-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True
77,2024-09-26,Peacock B03BD Premium,Bills & Utilities,Sale,-2.28,peacock x premium,True
85,2024-09-15,GOOGLE *Colab,Shopping,Sale,-9.99,google colab,True
93,2024-09-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
95,2024-09-03,OPENAI *CHATGPT SUBSCR,Shopping,Sale,-20.00,openai chatgpt subscr,True
97,2024-08-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True
138,2024-08-08,AMC 9640 ONLINE,Entertainment,Sale,-26.82,amc online,True
146,2024-07-29,Spotify USA,Bills & Utilities,Sale,-6.85,spotify usa,True

In [20]:
data[data['Is_Recurring']]['Merchant'].unique()

array(['google colab', 'openai chatgpt subscr', 'amc online',
       'spotify usa', 'peacock x premium'], dtype=object)